name: Trigger Concourse resource-check
description:
  Triggers a resource-check in a specific Concourse pipeline
branding:
  color: blue
  icon: rotate-cw

inputs:
  concourse-url:
    description: The base URL for your Concourse CI
    required: true
  concourse-team:
    description: The Concourse team where the pipeline lives
    required: true
    default: main
  concourse-pipeline:
    description: The Concourse pipeline where the resource lives
    required: true
  concourse-resource:
    description: The resource for which a check is to be triggered
    required: true
  concourse-webhook-token:
    description:
      The secret value used for the 'webhook_token' property of the Concourse
      resource
    required: true

runs:
  using: composite  
  steps:
    - name: Trigger a resource check in Concourse
      run: |
        function esc() {
            python3 -c "import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1]))" "$1"
        }

        url="${{ inputs.concourse-url }}"
        url+="/api/v1/teams/$(esc "${{ inputs.concourse-team }}")"
        url+="/pipelines/$(esc "${{ inputs.concourse-pipeline }}")"
        url+="/resources/$(esc "${{ inputs.concourse-resource }}")"
        url+="/check/webhook?webhook_token="

        echo "Querying URL: '${url}<redacted>'"

        url+=$(esc "${{ inputs.concourse-webhook-token }}")

        curl --silent --fail --show-error --location --request "POST" --url "${url}"
      shell: bash
